-- V1: 베이스라인 — ddl-auto=update 시절 Hibernate가 만들어 온 스키마를 그대로 옮긴 것.
-- 이 시점부터 스키마의 단일 권위는 마이그레이션 스크립트다. 엔티티를 바꾸면
-- (기존 스크립트 수정이 아니라) V2, V3... 를 추가한다 — 적용된 스크립트는 불변.
-- 이미 스키마가 있는 기존 DB에는 baseline-on-migrate가 이 파일을 건너뛰고 V1로 표시만 한다.

-- io.dbtower.registry.DatabaseInstance — 관제 대상으로 등록된 DB 인스턴스
-- type CHECK는 5기종 전부 포함 — 3기종 시절 제약이 enum 확장을 막았던 사고(VERIFICATION.md 18-3)의 재발 방지.
-- 앞으로 기종을 늘리면 이 제약의 재생성이 새 마이그레이션이 된다.
CREATE TABLE database_instance (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255)  NOT NULL,
    type       VARCHAR(255)  NOT NULL,
    host       VARCHAR(255)  NOT NULL,
    port       INTEGER       NOT NULL,
    db_name    VARCHAR(255)  NOT NULL,
    username   VARCHAR(255)  NOT NULL,
    password   VARCHAR(255)  NOT NULL,
    created_at TIMESTAMP(6)  NOT NULL,
    CONSTRAINT database_instance_pkey PRIMARY KEY (id),
    CONSTRAINT uk_database_instance_name UNIQUE (name),
    CONSTRAINT database_instance_type_check
        CHECK (type IN ('MYSQL', 'POSTGRESQL', 'MSSQL', 'MONGODB', 'ORACLE'))
);

-- io.dbtower.insight.QuerySnapshot — 특정 시각에 수집한 쿼리별 누적 통계 한 줄
CREATE TABLE query_snapshot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    instance_id   BIGINT           NOT NULL,
    captured_at   TIMESTAMP(6)     NOT NULL,
    query_id      VARCHAR(64)      NOT NULL,
    query_text    VARCHAR(4000),
    calls         BIGINT           NOT NULL,
    total_time_ms DOUBLE PRECISION NOT NULL,
    rows_examined BIGINT           NOT NULL,
    CONSTRAINT query_snapshot_pkey PRIMARY KEY (id)
);

-- instanceId 등치 + capturedAt 범위 조회용 복합 인덱스 (개선 아크 3, 실측은 VERIFICATION.md 9절)
CREATE INDEX idx_snapshot_instance_time ON query_snapshot (instance_id, captured_at);

-- io.dbtower.backup.BackupPolicyEntity — 인스턴스별 백업 정책 (인스턴스당 1개)
CREATE TABLE backup_policy_entity (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    instance_id      BIGINT       NOT NULL,
    interval_minutes INTEGER      NOT NULL,
    type             VARCHAR(255) NOT NULL,
    enabled          BOOLEAN      NOT NULL,
    last_run_at      TIMESTAMP(6),
    CONSTRAINT backup_policy_entity_pkey PRIMARY KEY (id),
    CONSTRAINT uk_backup_policy_instance UNIQUE (instance_id),
    CONSTRAINT backup_policy_entity_type_check
        CHECK (type IN ('FULL', 'LOG'))
);

-- io.dbtower.backup.BackupRun — 백업 실행 이력 한 건
CREATE TABLE backup_run (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    instance_id BIGINT        NOT NULL,
    started_at  TIMESTAMP(6)  NOT NULL,
    duration_ms BIGINT        NOT NULL,
    status      VARCHAR(255)  NOT NULL,
    detail      VARCHAR(1000),
    CONSTRAINT backup_run_pkey PRIMARY KEY (id),
    CONSTRAINT backup_run_status_check
        CHECK (status IN ('SUCCESS', 'FAILED'))
);

-- io.dbtower.security.PlatformUser — 플랫폼 사용자 (관리 대상 DB 계정과는 별개)
CREATE TABLE platform_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    CONSTRAINT platform_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk_platform_user_username UNIQUE (username),
    CONSTRAINT platform_user_role_check
        CHECK (role IN ('VIEWER', 'ADMIN'))
);
