-- V2: 감사 로그 (Phase A6) — "누가 언제 무엇을 했고 결과가 어땠나"를 플랫폼 메타 DB에 남긴다.
-- io.dbtower.audit.AuditEvent 매핑. 적용된 스크립트는 불변 — 변경은 V3+ 로 추가한다.
CREATE TABLE audit_event (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    occurred_at TIMESTAMP(6) NOT NULL,
    -- 사용자명 또는 'api-token'(Bearer 서비스 계정)
    principal   VARCHAR(255) NOT NULL,
    -- VIEWER/ADMIN — 로그인 실패처럼 역할 확정 전이면 NULL.
    -- CHECK 제약은 걸지 않는다: 역할 추가 때 제약 재생성 마이그레이션이 필요해지는 결합
    -- (database_instance.type의 enum 확장 사고와 같은 구조, VERIFICATION.md 18-3)을 감사 로그에까지 만들 이유가 없다.
    role        VARCHAR(255),
    -- HTTP 메서드 + 경로 요약 (예: 'POST /api/instances'), 로그인은 'LOGIN'
    action      VARCHAR(500) NOT NULL,
    -- 경로가 /api/instances/{id}/... 꼴이면 대상 인스턴스 id
    instance_id BIGINT,
    -- HTTP 상태 코드 (로그인도 200/401로 환산)
    outcome     INTEGER      NOT NULL,
    -- 요청 처리 시간(ms) — 요청 단위가 아닌 이벤트(로그인·인가 거부)는 NULL
    duration_ms BIGINT,
    CONSTRAINT audit_event_pkey PRIMARY KEY (id)
);

-- 조회 패턴은 "최신 N건"과 기간 검색 — 둘 다 occurred_at 인덱스가 받친다
CREATE INDEX idx_audit_event_occurred_at ON audit_event (occurred_at);
