-- V5: 가용성 SLI 원자료 (Phase D4) — io.dbtower.slo.HealthSample.
-- 헬스체크는 원래 요청 시점에만 계산하고 남기지 않아 "지난 기간 중 몇 %가 up이었나"를 물을 수 없었다.
-- 에러 버짓은 시계열이 있어야 계산되므로, 폴러(SloHealthPoller)가 주기적으로 up/down을 이 표에 남긴다.
-- 다운 샘플 한 개는 대략 수집 주기(dbtower.slo.availability.poll-ms)만큼의 다운타임을 뜻한다(버짓 산식의 근사).
CREATE TABLE health_sample (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    instance_id BIGINT       NOT NULL,
    sampled_at  TIMESTAMP(6) NOT NULL,
    up          BOOLEAN      NOT NULL,
    ping_millis BIGINT       NOT NULL,
    CONSTRAINT health_sample_pkey PRIMARY KEY (id)
);

-- instance_id 등치 + sampled_at 범위(윈도우 집계·번인창)용 복합 인덱스 — 등치 컬럼을 선두에.
CREATE INDEX idx_health_sample_instance_time ON health_sample (instance_id, sampled_at);
