@startuml
title <size:24>Score</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("DbtowerApplication_boundary", "DbtowerApplication", $tags="") {
  Container_Boundary("DbtowerApplication.DbtowerApplication_boundary", "DbtowerApplication", $tags="") {
    Component(DbtowerApplication.DbtowerApplication.Slo, "Slo", $techn="Module", $descr="", $tags="", $link="")
    Component(DbtowerApplication.DbtowerApplication.Insight, "Insight", $techn="Module", $descr="", $tags="", $link="")
    Component(DbtowerApplication.DbtowerApplication.Advisor, "Advisor", $techn="Module", $descr="", $tags="", $link="")
    Component(DbtowerApplication.DbtowerApplication.Score, "Score", $techn="Module", $descr="", $tags="", $link="")
    Component(DbtowerApplication.DbtowerApplication.Registry, "Registry", $techn="Module", $descr="", $tags="", $link="")
    Component(DbtowerApplication.DbtowerApplication.Backup, "Backup", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(DbtowerApplication.DbtowerApplication.Score, DbtowerApplication.DbtowerApplication.Registry, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Score, DbtowerApplication.DbtowerApplication.Insight, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Score, DbtowerApplication.DbtowerApplication.Advisor, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Score, DbtowerApplication.DbtowerApplication.Slo, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Score, DbtowerApplication.DbtowerApplication.Backup, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Backup, DbtowerApplication.DbtowerApplication.Registry, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Advisor, DbtowerApplication.DbtowerApplication.Registry, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Advisor, DbtowerApplication.DbtowerApplication.Insight, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Insight, DbtowerApplication.DbtowerApplication.Registry, "listens to", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Insight, DbtowerApplication.DbtowerApplication.Registry, "uses", $techn="", $tags="", $link="")
Rel(DbtowerApplication.DbtowerApplication.Slo, DbtowerApplication.DbtowerApplication.Registry, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml